steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fish2eat-api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fish2eat-api']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fish2eat-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/fish2eat-api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-southeast2'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/fish2eat-api'
